spring.application.name=productos-service
server.port=8081

# En la evaluacion esta URL apunta al endpoint de Amazon Aurora PostgreSQL.
spring.datasource.url=jdbc:postgresql://localhost:5432/product_db
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
