spring.application.name=bff
server.port=8080

productos.service.url=http://localhost:8081
carrito.service.url=http://localhost:8082

cognito.issuer-uri=${COGNITO_ISSUER_URI:https://cognito-idp.us-east-1.amazonaws.com/us-east-1_k6i5fiOXd}
cognito.client-id=${COGNITO_CLIENT_ID:54029vs6af51eq3psh8pgn9vs0}
