spring.application.name=carrito-service
server.port=8082

# En la evaluacion esta URL apunta al endpoint de Amazon Aurora PostgreSQL, base cart_db.
spring.datasource.url=jdbc:postgresql://localhost:5432/cart_db
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

productos.service.url=http://localhost:8081
